/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTS_A;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class UTS_Amir extends javax.swing.JFrame {

    /**
     * Creates new form UTS_Amir
     */
    public UTS_Amir() {
        initComponents();
    }

    public void reset() {
        txtKode.setText(null);
        txtNama.setText(null);
        txtMbi.setText(null);
        txtMbl.setText(null);
        txtTarif.setText(null);
        txtDiskon.setText(null);
    }

    public void diskon() {
        int A;
        int B;
        int C;
        int D;
        A = Integer.parseInt(txtMbi.getText());
        B = Integer.parseInt(txtMbl.getText());
        C = Integer.parseInt(txtTarif.getText());
        D = (int) (C * 97 / 100);
        if (A - B > 20) {
            txtTarif.setText(String.valueOf(D));
        } else {
            txtTarif.setText(String.valueOf(C));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtMbi = new javax.swing.JTextField();
        txtMbl = new javax.swing.JTextField();
        txtTarif = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Diskon");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel2.setText("Kode Pelanggan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel3.setText("Tarif");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setText("Meter bulan ini");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel5.setText("Meter bulan lalu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel6.setText("Nama");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        jPanel1.add(txtDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 290, -1));

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });
        jPanel1.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 290, -1));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 290, -1));
        jPanel1.add(txtMbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 290, -1));
        jPanel1.add(txtMbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 290, -1));
        jPanel1.add(txtTarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 290, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "MBI", "MBL", "Tarif", "Diskon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 470, 180));

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 455);

        setSize(new java.awt.Dimension(554, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        diskon();
        if (txtKode.getText().trim().equals("") || txtNama.getText().trim().equals("") || txtMbi.getText().trim().equals("") || txtMbl.getText().trim().equals("") || txtTarif.getText().trim().equals("") || txtDiskon.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Tidak boleh ada data yang kosong \n Input ulang");
        } else {
            model.addRow(new Object[]{txtKode.getText(), txtNama.getText(), txtMbi.getText(), txtMbl.getText(), txtTarif.getText(), txtDiskon.getText()});
            //JOptionPane.showMessageDialog(null, "Data berhasil di input");
        }
        reset();

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam tabel");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
            }
        } else {
            if (txtKode.getText().trim().equals("") || txtNama.getText().trim().equals("") || txtMbi.getText().trim().equals("") || txtMbl.getText().trim().equals("") || txtTarif.getText().trim().equals("") || txtDiskon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Tidak boleh ada data yang kosong \n Input ulang");
            } else {
                diskon();
                model.setValueAt(txtKode.getText(), jTable1.getSelectedRow(), 0);
                model.setValueAt(txtNama.getText(), jTable1.getSelectedRow(), 1);
                model.setValueAt(txtMbi.getText(), jTable1.getSelectedRow(), 2);
                model.setValueAt(txtMbl.getText(), jTable1.getSelectedRow(), 3);
                model.setValueAt(txtTarif.getText(), jTable1.getSelectedRow(), 4);
                model.setValueAt(txtDiskon.getText(), jTable1.getSelectedRow(), 5);
            }
        }
        reset();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam tabel");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
            }
        } else {
            model.removeRow(jTable1.getSelectedRow());
        }
        reset();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        txtKode.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        txtNama.setText(model.getValueAt(jTable1.getSelectedRow(), 1).toString());
        txtMbi.setText(model.getValueAt(jTable1.getSelectedRow(), 2).toString());
        txtMbl.setText(model.getValueAt(jTable1.getSelectedRow(), 3).toString());
        txtTarif.setText(model.getValueAt(jTable1.getSelectedRow(), 4).toString());
        txtDiskon.setText(model.getValueAt(jTable1.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTS_Amir.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTS_Amir.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTS_Amir.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTS_Amir.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS_Amir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtMbi;
    private javax.swing.JTextField txtMbl;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTarif;
    // End of variables declaration//GEN-END:variables
}
